# Generated by Django 5.1.4 on 2024-12-31 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_inventory_sold_item_stored_place_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('ZAMOWIONE', 'ZAMOWIONE'), ('DOSTEPNY', 'DOSTEPNY'), ('SPRZEDANY', 'SPRZEDANY')], default='ZAMOWIONE'),
        ),
        migrations.AddField(
            model_name='sold_item',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
